# Generated by Django 5.2 on 2025-04-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.IntegerField(choices=[(0, 'Single Line Input'), (1, 'Multi Line Input'), (2, 'Checkbox'), (3, 'Dropdown'), (4, 'Radio'), (5, 'Date'), (6, 'Time'), (7, 'Date and Time'), (8, 'Number')]),
        ),
    ]
