# Generated by Django 5.2 on 2025-04-13 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_property_description_alter_property_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='object',
            new_name='object_id',
        ),
    ]
