# Generated by Django 5.2 on 2025-04-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_object_id_property_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='type_extra',
            field=models.TextField(blank=True),
        ),
    ]
