# Generated by Django 5.2 on 2025-04-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_property_type_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.IntegerField(choices=[(0, 'Single Line Input'), (1, 'Multi Line Input'), (2, 'Dropdown'), (3, 'Radio'), (4, 'Date'), (5, 'Time'), (6, 'Date and Time'), (7, 'Number')]),
        ),
    ]
